[YKN-441] : Merging PRs with multiple commits, produce unexpected results
hv-actions/change-detection-builder pull request #4
Opened 2023-07-13 10:44 UTC by AdityaHitachi

Added this GitHub marketplace action tj-actions/changed-files@v37 for file change detection in both PR and MR workflows. Also changed the Python script to fetch the changed module path as Output using
${{ steps.change_detection.outputs.changed_modules_path }} variable

2023-07-13 14:11 UTC, cardosov requested changes

2023-07-13 14:11 UTC, cardosov commented on maven.py
> +    print("Parent Dirs name")
Is this important to be included? Is it logging enrichment maybe?

2023-07-13 14:11 UTC, cardosov commented on maven.py
> +        print(f'{name}={value}', file=fh)
New empty (no white-spaces) line at the bottom of the file.

2023-07-13 14:11 UTC, cardosov commented on action.yaml
> +  changed_modules_path:
If you want to rename the output, maybe `changed_modules_paths` makes more sense? I'm probably ok with remaining it as `change_modules`. The output name change would mean that the workflows that are using the this step already need to be changed to start using this new name. What do you think?

2023-07-14 06:54 UTC, AdityaHitachi commented on maven.py
> +    print("Parent Dirs name")
Yes, it is not required.  It is logging  enrichment only.

2023-07-14 07:12 UTC, AdityaHitachi commented on action.yaml
> +  changed_modules_path:
Yes, It would be more efficient to stick with ```change_modules``` since it is already being used in workflows, avoiding the need for any additional alterations.

2023-07-14 07:48 UTC, AdityaHitachi commented on action.yaml
> +      shell: bash
Added

2023-07-14 07:48 UTC, AdityaHitachi commented on maven.py
> +        print(f'{name}={value}', file=fh)
added

2023-07-14 09:07 UTC, cardosov approved these changes

2023-07-17 07:39 UTC, merged